import type { Metadata, Viewport } from "next";

import { Sx } from "@/common/ui/base/vars";

export const appViewport: Viewport = {
  themeColor: Sx.color.background,
};

export const appMetadata: Metadata = {
  title: "App Delivery",
  description: "Generated by create next app",
  manifest: "/manifest.json",

  appleWebApp: {
    title: "App Delivery",
    statusBarStyle: "default",
    startupImage: {
      url: "/images/screen-720-1280.png",
    },
  },

  other: {
    "mobile-web-app-capable": "yes",
  },
};
